<a href="https://colab.research.google.com/github/ritashreemukherjee123/Project-1-Applied-Search-Intelligence-Google-Search-Ranking-Discoverability.-/blob/main/work/w03_data_contract.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/flyrank-bih/flyrank-ml-internship-starter/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

**Search Intelligence data Contract - An active, provable commitment written before any ML modeling.**

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

Best Data for Lane 2 are the warehouse release (`dim_content` + `fact_content_daily_performance`) or the starter dataset.
Here, we are using the warehouse dataset.

**"Unit of analysis"**: Formal Version of **"Grain"**.

Here, `dim_content` has **"one row per pseudonymized content item"** which is the Grain of this Table. `dim_content` deduplicates content into one row per pseudonymized content item.

In simple words, **One row = one piece of content (article, feed, comparison, etc.)** for a specific client and keyword.

`fact_content_daily_performance` has daily x client x content as Grain which means **one row per report date, pseudonymized client, and pseudonymized content item**. The data **cuts off the freshest 3 days**: report_date <= DATE_SUB(DATE('2026-07-03'), INTERVAL 3 DAY) (so daily facts run through 2026-06-30).

In [1]:
%pip -q install duckdb huggingface_hub

In [2]:
import os, getpass

# Token order: env var -> Colab Secret -> prompt (last resort).
# Use a Colab Secret named HF_TOKEN (the key panel on the left) so the prompt never
# fires: if Colab reconnects while a getpass prompt is open, the kernel waits on it
# forever ('Resuming execution...') and you have to restart the runtime.
HF_TOKEN = os.environ.get('HF_TOKEN')
if not HF_TOKEN:
    try:
        from google.colab import userdata
        HF_TOKEN = userdata.get('HF_TOKEN')
    except Exception:
        pass
HF_TOKEN = HF_TOKEN or getpass.getpass('Ritashree')

Ritashree··········

**Important**: That count over the daily fact touched **Parquet metadata, not data** — it finished in seconds
even though the table has ~79M rows. That is the whole workflow: push the heavy lifting into
DuckDB SQL, bring only small results into pandas.

The `REL` variable defines the base URL for the dataset warehouse. The `TABLES` dictionary maps user-friendly table names to DuckDB SQL expressions that specify how to read various Parquet files from that Hugging Face repository, some of which use a `glob pattern(**/*.parquet)` to read multiple files within a directory.

In [3]:
##Connecting DuckDB to the release which would autheticate every query written
import duckdb

con = duckdb.connect()
con.execute(f"CREATE OR REPLACE SECRET hf (TYPE huggingface, TOKEN '{HF_TOKEN}')")

REL = 'hf://datasets/FlyRank/internship-warehouse'
TABLES = {
    'dim_clients':                f"read_parquet('{REL}/dim_clients.parquet')",
    'dim_content':                f"read_parquet('{REL}/dim_content.parquet')",
    'fact_daily':                 f"read_parquet('{REL}/fact_content_daily_performance/**/*.parquet')",
    'fact_daily_sample':          f"read_parquet('{REL}/fact_content_daily_performance_sample.parquet')",
    'fact_query_90d':             f"read_parquet('{REL}/fact_content_query_90d.parquet')",
}

for name, src in TABLES.items():
    n = con.sql(f'SELECT COUNT(*) FROM {src}').fetchone()[0]
    print(f'{name:22} {n:>12,} rows')

dim_clients                     104 rows
dim_content                 519,606 rows

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

fact_daily               78,835,655 rows
fact_daily_sample        11,694,072 rows
fact_query_90d            2,414,248 rows

In [4]:
# Columns of dim_content

result_dim_content = con.sql(f"""
SELECT *
FROM {TABLES['dim_content']}
LIMIT 5;
""").fetchdf()
print(result_dim_content)

            client_hash_id           content_hash_id  \
0  client_04660893ae39614a  content_004de9653278b5a4
1  client_04660893ae39614a  content_00dc5efae381b2ab
2  client_04660893ae39614a  content_01410f2556c327ac
3  client_04660893ae39614a  content_019f27f634053ca7
4  client_04660893ae39614a  content_01efa71faea45dcc

            keyword_hash_id           url_hash_id  keyword_char_count  \
0  keyword_e754999ab88dd9f2  url_d6091f18cf628794                  22
1  keyword_4329d7aede8e208b  url_3a66d2f2e36823ca                  31
2  keyword_9b08047d3d2a0406  url_809eda7a7e20b3b2                  22
3  keyword_e7cec7ab1804c1c2  url_5fb42bafc4399861                  14
4  keyword_56b0062a1d8b7524  url_ece0abc3e5fb75f9                  24

   keyword_token_count  url_char_count content_created_date  \
0                    4             108           2026-05-30
1                    6              95           2026-06-12
2                    5              82           2026-05-09
3                    3              92           2026-06-15
4                    6              98           2026-05-21

  content_updated_date     content_type  ...  category_count  \
0           2026-07-01  keyword article  ...               3
1           2026-07-01  keyword article  ...               4
2           2026-07-01  keyword article  ...               4
3           2026-06-15  keyword article  ...               4
4           2026-06-01  keyword article  ...               4

   keyword_created_date            provider_used              model_used  \
0            2026-05-12  gemini-generate-content  gemini-3-flash-preview
1            2026-06-01  gemini-generate-content  gemini-3-flash-preview
2            2026-05-06  gemini-generate-content  gemini-3-flash-preview
3            2026-06-01  gemini-generate-content  gemini-3-flash-preview
4            2026-05-12  gemini-generate-content  gemini-3-flash-preview

  char_count  word_count  last_optimized_date optimization_eligible_date  \
0      15682        2555                  NaT                        NaT
1      15438        2430                  NaT                        NaT
2      16576        2645                  NaT                        NaT
3      15457        2522                  NaT                        NaT
4      15776        2552                  NaT                        NaT

  is_published is_deleted
0         True      False
1         True      False
2         True      False
3         True      False
4         True      False

[5 rows x 26 columns]

#Duplicate Check

6390 rows of duplicate combinations which may indicate a missing dimension, legitimate multiple observations, or a need for
aggregation.

In [5]:
duplicate_check = con.sql(f"""
SELECT report_date, client_hash_id, content_hash_id,
COUNT(*) AS n_rows FROM {TABLES['fact_daily_sample']}
GROUP BY report_date, client_hash_id, content_hash_id
HAVING COUNT(*) > 1 ORDER BY n_rows DESC;""").fetchdf()

print(duplicate_check)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

     report_date           client_hash_id           content_hash_id  n_rows
0     2026-06-13  client_1a730cb2640a1abf  content_1a0c3a8cc6bdd5bc       2
1     2026-06-13  client_1a730cb2640a1abf  content_8d5a5293688d7d8e       2
2     2026-06-13  client_1a730cb2640a1abf  content_b40e27e07768f907       2
3     2026-06-13  client_1a730cb2640a1abf  content_965b9031838c130f       2
4     2026-06-13  client_1a730cb2640a1abf  content_fa351551b6d49870       2
...          ...                      ...                       ...     ...
6385  2026-06-30  client_06d356715a8ff3b6  content_9a4bb488845c9327       2
6386  2026-06-30  client_06d356715a8ff3b6  content_d96a469f982cff1c       2
6387  2026-06-30  client_06d356715a8ff3b6  content_f497146ba51bada2       2
6388  2026-06-30  client_06d356715a8ff3b6  content_45a4e4755090bc02       2
6389  2026-06-30  client_06d356715a8ff3b6  content_b21f0784b540332c       2

[6390 rows x 4 columns]

This code performs a SQL query that joins two tables: `fact_query_90d`(aliased as t1) and `dim_content`(aliased as t2). It selects various columns from both tables, including client_hash_id, content_hash_id (from both tables, aliased to distinguish them), query_hash_id, content_type, content_created_date, content_updated_date, and query_char_count. The tables are joined on content_hash_id, which means it combines rows where the content identifier is the same in both.

In [6]:
#Same as before except the count value of the duplicate rows

duplicate_check = con.sql(f"""
SELECT report_date, client_hash_id, content_hash_id,
COUNT(*) AS n_rows FROM {TABLES['fact_daily_sample']} GROUP
BY report_date, client_hash_id, content_hash_id
HAVING COUNT(*) > 1 ORDER BY n_rows DESC
LIMIT 5;""").fetchdf()

print(duplicate_check)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  report_date           client_hash_id           content_hash_id  n_rows
0  2026-06-13  client_1a730cb2640a1abf  content_1a0c3a8cc6bdd5bc       2
1  2026-06-13  client_1a730cb2640a1abf  content_8d5a5293688d7d8e       2
2  2026-06-13  client_1a730cb2640a1abf  content_b40e27e07768f907       2
3  2026-06-13  client_1a730cb2640a1abf  content_965b9031838c130f       2
4  2026-06-13  client_1a730cb2640a1abf  content_fa351551b6d49870       2

In [7]:
#Join content facts to dim_content on content_hash_id.
result = con.sql(f"""
SELECT
    t1.client_hash_id,
    t1.content_hash_id AS fact_content_hash_id,
    t2.content_hash_id AS dim_content_hash_id,
    t1.query_hash_id,
    t1.query_char_count,
    t2.content_type,
    t2.content_created_date,
    t2.content_updated_date,
    t1.query_char_count

FROM
    {TABLES['fact_query_90d']} AS t1
JOIN
    {TABLES['dim_content']} AS t2
ON
    t1.content_hash_id = t2.content_hash_id
LIMIT 5;
""").fetchdf()
print(result)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

            client_hash_id      fact_content_hash_id  \
0  client_08a6a72ff48e62c0  content_5f6556f5a53e47f0
1  client_08a6a72ff48e62c0  content_5f6c0644690c7bda
2  client_08a6a72ff48e62c0  content_5f6c0644690c7bda
3  client_08a6a72ff48e62c0  content_5f6c0644690c7bda
4  client_08a6a72ff48e62c0  content_5f6c0644690c7bda

        dim_content_hash_id           query_hash_id  query_char_count  \
0  content_5f6556f5a53e47f0  query_4225de77a704f13b                22
1  content_5f6c0644690c7bda  query_5334a84c25d08ae8                28
2  content_5f6c0644690c7bda  query_58d07c42a27e46a6                20
3  content_5f6c0644690c7bda  query_871044f200f69372                16
4  content_5f6c0644690c7bda  query_ba5ee754917c395e                13

      content_type content_created_date content_updated_date  \
0  keyword article           2026-04-02           2026-05-20
1  keyword article           2025-07-31           2026-02-25
2  keyword article           2025-07-31           2026-02-25
3  keyword article           2025-07-31           2026-02-25
4  keyword article           2025-07-31           2026-02-25

   query_char_count_1
0                  22
1                  28
2                  20
3                  16
4                  13

In [8]:
# Join client-level facts to dim_clients on client_hash_id.
result_client_join = con.sql(f"""
SELECT
    t1.client_hash_id AS fact_client_hash_id,
    t1.content_hash_id,
    t1.query_hash_id,
    t2.client_hash_id AS dim_client_hash_id,
    t2.client_created_date,
    t1.query_char_count
FROM
    {TABLES['fact_query_90d']} AS t1
JOIN
    {TABLES['dim_clients']} AS t2
ON
    t1.client_hash_id = t2.client_hash_id
LIMIT 5;
""").fetchdf()
print(result_client_join)

       fact_client_hash_id           content_hash_id           query_hash_id  \
0  client_08a6a72ff48e62c0  content_447894f2faf0d2bc  query_58b1b001f839d699
1  client_08a6a72ff48e62c0  content_447894f2faf0d2bc  query_922b8eca2a24cd34
2  client_08a6a72ff48e62c0  content_447894f2faf0d2bc  query_9f0c36a6ae2a6a99
3  client_08a6a72ff48e62c0  content_447894f2faf0d2bc  query_a032820b5467e996
4  client_08a6a72ff48e62c0  content_447894f2faf0d2bc  query_ba1a2f131961c5da

        dim_client_hash_id client_created_date  query_char_count
0  client_08a6a72ff48e62c0          2025-05-26                17
1  client_08a6a72ff48e62c0          2025-05-26                34
2  client_08a6a72ff48e62c0          2025-05-26                16
3  client_08a6a72ff48e62c0          2025-05-26                24
4  client_08a6a72ff48e62c0          2025-05-26                18

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

In [9]:
content_analysis_result = con.sql(f"""
SELECT

    t1.content_hash_id AS fact_content_hash_id,
    t2.content_hash_id AS dim_content_hash_id,
    t2.content_type,
    t2.content_created_date,
    t2.content_updated_date
FROM
    {TABLES['fact_daily_sample']} AS t1
JOIN
    {TABLES['dim_content']} AS t2
ON
    t1.content_hash_id = t2.content_hash_id
LIMIT 5;
""").fetchdf()
print(content_analysis_result)

       fact_content_hash_id       dim_content_hash_id     content_type  \
0  content_1a6296faee432dae  content_1a6296faee432dae  keyword article
1  content_73f21e612565035a  content_73f21e612565035a  keyword article
2  content_5a5be514ff559598  content_5a5be514ff559598  keyword article
3  content_05b377d0c8a5cfd8  content_05b377d0c8a5cfd8  keyword article
4  content_dc34c661d63e55a9  content_dc34c661d63e55a9  keyword article

  content_created_date content_updated_date
0           2025-02-05           2026-05-20
1           2025-02-05           2026-05-20
2           2025-02-05           2026-05-20
3           2025-02-05           2026-05-20
4           2025-02-05           2026-05-20

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

**Grain**: Already stated which are the grain or unit of analysis are for each tables of data.

In [10]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

# dim content grain
dim_content_grain = f"""
SELECT
    COUNT(*) AS rows,
    COUNT(DISTINCT content_hash_id) AS distinct_content,
    COUNT(DISTINCT (client_hash_id, content_hash_id)) AS distinct_client_content
FROM {TABLES['dim_content']}
"""

con.execute(dim_content_grain).df()

     rows  distinct_content  distinct_client_content
0  519606            519606                   519606

In [11]:
#Grain of fact_daily_sample, with time window (report date, month of report)
# showing 'daily x client x content' grain.

result_fact_daily_sample = con.sql(f"""
SELECT report_date, client_hash_id, content_hash_id
FROM {TABLES['fact_daily_sample']}
LIMIT 5;
""").fetchdf()
print(result_fact_daily_sample)

  report_date           client_hash_id           content_hash_id
0  2026-06-01  client_3ffa76342f366962  content_1a6296faee432dae
1  2026-06-01  client_3ffa76342f366962  content_73f21e612565035a
2  2026-06-01  client_3ffa76342f366962  content_5a5be514ff559598
3  2026-06-01  client_3ffa76342f366962  content_05b377d0c8a5cfd8
4  2026-06-01  client_3ffa76342f366962  content_dc34c661d63e55a9

**Counts**, here, specify slice’s row count and date span, and availability.

In [12]:
unique_content_count = con.sql(f"""
SELECT COUNT(DISTINCT content_hash_id)
FROM {TABLES['dim_content']}
""").fetchone()[0]
print(f"Unique content_hash_id in dim_content: {unique_content_count:,} (should match total dim_content rows: {con.sql(f'SELECT COUNT(*) FROM {TABLES['dim_content']}').fetchone()[0]:,})")

# Verify the count for fact_daily_sample
fact_daily_sample_row_count = con.sql(f"""
SELECT COUNT(*)
FROM {TABLES['fact_daily_sample']}
""").fetchone()[0]
print(f"Total rows in fact_daily_sample: {fact_daily_sample_row_count:,}")

# Verify the grain of fact_daily_sample by counting unique combinations of (report_date, client_hash_id, content_hash_id)
unique_fact_daily_sample_grain_count = con.sql(f"""
SELECT COUNT(DISTINCT (report_date, client_hash_id, content_hash_id))
FROM {TABLES['fact_daily_sample']}
""").fetchone()[0]
print(f"Unique (report_date, client_hash_id, content_hash_id) combinations in fact_daily_sample: {unique_fact_daily_sample_grain_count:,}")

# If the unique grain count matches the total row count, it confirms the grain
if unique_fact_daily_sample_grain_count == fact_daily_sample_row_count:
    print("The grain of 'daily x client x content' for fact_daily_sample is confirmed by unique combinations.")
else:
    print("The grain of 'daily x client x content' for fact_daily_sample does not uniquely identify all rows.")

Unique content_hash_id in dim_content: 519,606 (should match total dim_content rows: 519,606)
Total rows in fact_daily_sample: 11,694,072

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Unique (report_date, client_hash_id, content_hash_id) combinations in fact_daily_sample: 11,687,682
The grain of 'daily x client x content' for fact_daily_sample does not uniquely identify all rows.

### Temporal Coverage (Time Windows)

In [13]:
# Get the min and max report_date from fact_daily_sample
date_window_fact_daily_sample = con.sql(f"""
SELECT MIN(report_date), MAX(report_date)
FROM {TABLES['fact_daily_sample']}
""").fetchdf()
print(f"Report date window for fact_daily_sample: {date_window_fact_daily_sample.iloc[0, 0]} to {date_window_fact_daily_sample.iloc[0, 1]}")

Report date window for fact_daily_sample: 2026-06-01 00:00:00 to 2026-06-30 00:00:00

In [14]:
temporal_coverage = f"""
SELECT
    MIN(report_date) AS min_date,
    MAX(report_date) AS max_date,
    COUNT(DISTINCT report_date) AS n_dates,
    COUNT(DISTINCT client_hash_id) AS n_clients,
    COUNT(DISTINCT content_hash_id) AS n_contents
FROM {TABLES['fact_daily']}
"""

con.execute(temporal_coverage).df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

    min_date   max_date  n_dates  n_clients  n_contents
0 2025-01-27 2026-06-30      520         70      427292

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

1. **Unbalanced History**:
   - The `fact_daily` table explicitly 'cuts off the freshest 3 days' (e.g., data only up to 2026-06-30).

2. **GSC-only early rows (Google Search Console-only early rows)**:
    - While not explicitly stated as Google Search Console (GSC) data, the context of 'Search Intelligence'. But, even if GSC is the primary source, it would depend on the GSC's data retention policies.

3. **Window Overlaps**: No, the data does not state any window overlap as distinct dates are seen.

In [15]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

per_client_history_depth = f"""
SELECT
    client_hash_id,
    MIN(report_date) AS first_date,
    MAX(report_date) AS last_date,
    COUNT(DISTINCT report_date) AS n_dates
FROM {TABLES['fact_daily']}
GROUP BY client_hash_id
ORDER BY first_date
"""

client_history = con.execute(per_client_history_depth).df()

client_history.head()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

            client_hash_id first_date  last_date  n_dates
0  client_9958f0a7ae1df715 2025-01-27 2026-06-30      520
1  client_ff644d8251367cbb 2025-01-27 2026-06-30      514
2  client_73cda7b4e4f265ea 2025-02-11 2026-06-30      505
3  client_fef1a8f436438636 2025-03-11 2026-06-30      477
4  client_62f4a7e64f5e0096 2025-06-07 2026-06-30      389

In [16]:
client_history["history_days"] = (
    client_history["last_date"] - client_history["first_date"]
).dt.days + 1

client_history["history_days"].describe()

count     70.000000
mean     220.457143
std      125.075825
min       34.000000
25%      114.000000
50%      235.000000
75%      280.000000
max      520.000000
Name: history_days, dtype: float64

In [17]:
client_history.sort_values("history_days").head(10)

             client_hash_id first_date  last_date  n_dates  history_days
69  client_aef6ffea193da149 2026-05-28 2026-06-30       34            34
67  client_a22068e339bf95f5 2026-05-22 2026-06-30       40            40
68  client_04660893ae39614a 2026-05-22 2026-06-30       40            40
65  client_c7c2962f1c9c3089 2026-05-09 2026-06-30       53            53
66  client_1a8bf67cad4ee525 2026-05-09 2026-06-30       53            53
64  client_c353557474475e51 2026-04-30 2026-06-30       52            62
63  client_7de9989c909e91a5 2026-04-20 2026-06-30       72            72
62  client_9c26c096d6e57253 2026-04-16 2026-06-30       76            76
61  client_0b245132bb722950 2026-04-06 2026-06-30       86            86
59  client_8ddc46da5414ffd8 2026-04-02 2026-06-30       90            90

In [18]:
# Window Overlaps

# 1. Get the min and max report_date from fact_daily_sample
min_max_daily_sample = con.sql(f"""
SELECT MIN(report_date) AS min_date, MAX(report_date) AS max_date
FROM {TABLES['fact_daily_sample']}
""").fetchdf()
print(f"Fact Daily Sample Date Range: {min_max_daily_sample['min_date'].iloc[0]} to {min_max_daily_sample['max_date'].iloc[0]}")

Fact Daily Sample Date Range: 2026-06-01 00:00:00 to 2026-06-30 00:00:00

In [19]:
#dim_clients start date
dim_client_start_date = f"""
SELECT
    client_hash_id,
    gsc_data_start,
    ga4_data_start
FROM {TABLES['dim_clients']}
ORDER BY gsc_data_start
"""

client_starts = con.execute(dim_client_start_date).df()

client_starts.head()

            client_hash_id gsc_data_start ga4_data_start
0  client_9958f0a7ae1df715     2025-01-27     2025-10-29
1  client_ff644d8251367cbb     2025-01-27     2025-10-29
2  client_73cda7b4e4f265ea     2025-02-11     2026-03-24
3  client_fef1a8f436438636     2025-03-11     2026-03-06
4  client_62f4a7e64f5e0096     2025-06-07            NaT

Checking Missingness

###**Missingness**

Column	Missing	About

client_hash_id	0%	none, as expected for a key

gsc_data_start	35.6%	37 of 104 clients

ga4_data_start	51.0%	53 of 104 clients

In [20]:
print(client_starts.isna().mean())
print(client_starts["gsc_data_start"].describe())

client_hash_id    0.000000
gsc_data_start    0.355769
ga4_data_start    0.509615
dtype: float64
count                            67
mean     2025-11-17 00:42:59.104477
min             2025-01-27 00:00:00
25%             2025-09-24 00:00:00
50%             2025-11-05 00:00:00
75%             2026-02-19 00:00:00
max             2026-06-02 00:00:00
Name: gsc_data_start, dtype: object

In [21]:
#Missingness by content type

content_type_missingness = f"""
SELECT
    content_type,
    COUNT(*) AS n_rows
FROM {TABLES['dim_content']}
GROUP BY content_type
ORDER BY n_rows DESC
"""

con.execute(content_type_missingness).df()

         content_type  n_rows
0     keyword article  459174
1      feedly article   57024
2  comparison article    3408

For important metrics, joining only enough information to calculate missingness.

In [22]:
q = f"""
SELECT
    d.content_type,
    COUNT(*) AS rows,

    AVG(CASE WHEN f.gsc_impressions IS NULL THEN 1 ELSE 0 END) AS impressions_null_pct,
    AVG(CASE WHEN f.gsc_clicks IS NULL THEN 1 ELSE 0 END) AS clicks_null_pct,
    AVG(CASE WHEN f.gsc_avg_position IS NULL THEN 1 ELSE 0 END) AS position_null_pct,

    AVG(CASE WHEN f.ga4_sessions IS NULL THEN 1 ELSE 0 END) AS sessions_null_pct

FROM {TABLES['fact_daily']} f
LEFT JOIN {TABLES['dim_content']} d
  ON f.client_hash_id = d.client_hash_id
 AND f.content_hash_id = d.content_hash_id

GROUP BY d.content_type
ORDER BY rows DESC
"""

missing_by_type = con.execute(q).df()

missing_by_type

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,content_type,rows,impressions_null_pct,clicks_null_pct,position_null_pct,sessions_null_pct
0,keyword article,67119441,0.00146,0.00146,0.582241,0.372731
1,feedly article,11262186,0.00000,0.00000,0.938812,0.405448
2,comparison article,454028,0.00000,0.00000,0.468848,0.113702

NULL vs zero vs non-zero

Out of 78.8M+ rows,

Share	About

**NULL is	0.12%	~98,000 rows**

**Zero is 63.1%	~49.8M rows**

**Non-zero is 36.7%	~29.0M rows**

NULL        = missing/unobserved

0           = potentially observed zero

non-zero    = observed positive value

In [23]:
#For GSC impressions
q = f"""
SELECT
    COUNT(*) AS total_rows,

    AVG(CASE
        WHEN gsc_impressions IS NULL THEN 1
        ELSE 0
    END) AS null_pct,

    AVG(CASE
        WHEN gsc_impressions = 0 THEN 1
        ELSE 0
    END) AS zero_pct,

    AVG(CASE
        WHEN gsc_impressions > 0 THEN 1
        ELSE 0
    END) AS nonzero_pct

FROM {TABLES['fact_daily']}
"""

con.execute(q).df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   total_rows  null_pct  zero_pct  nonzero_pct
0    78835655  0.001243  0.631283     0.367474

In [24]:
con.sql(f"""
    SELECT gsc_data_available, ga4_data_available,
           COUNT(*) AS n,
           AVG((gsc_impressions = 0)::INT) AS zero_impr_share
    FROM {TABLES['fact_daily']}
    GROUP BY 1, 2 ORDER BY n DESC
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   gsc_data_available  ga4_data_available         n  zero_impr_share
0               False               False  28912779              1.0
1               False                <NA>  20492434              1.0
2                True               False  17373783              0.0
3                True                <NA>   9142893              0.0
4                True                True   2453375              0.0
5               False                True    362385              1.0
6                <NA>               False     97311              NaN
7                <NA>                True       695              NaN

In [25]:
#gsc_avg_position = 0 check

q = f"""
SELECT
    COUNT(*) AS total_rows,

    SUM(CASE WHEN gsc_avg_position = 0 THEN 1 ELSE 0 END)
        AS zero_position_rows,

    SUM(CASE WHEN gsc_avg_position IS NULL THEN 1 ELSE 0 END)
        AS null_position_rows,

    SUM(CASE WHEN gsc_avg_position > 0 THEN 1 ELSE 0 END)
        AS positive_position_rows

FROM {TABLES['fact_daily']}
"""

position_check = con.execute(q).df()

position_check

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   total_rows  zero_position_rows  null_position_rows  positive_position_rows
0    78835655           1393857.0          49865654.0              27576144.0

In [26]:
#GSC position semantics
q = f"""
SELECT
    gsc_data_available,
    COUNT(*) AS rows,
    SUM(CASE WHEN gsc_avg_position = 0 THEN 1 ELSE 0 END) AS zero_position,
    SUM(CASE WHEN gsc_avg_position IS NULL THEN 1 ELSE 0 END) AS null_position,
    SUM(CASE WHEN gsc_avg_position > 0 THEN 1 ELSE 0 END) AS positive_position
FROM {TABLES['fact_daily_sample']}
GROUP BY 1
ORDER BY 1
"""

con.execute(q).df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,gsc_data_available,rows,zero_position,null_position,positive_position
0,False,7815135,0.0,7815135.0,0.0
1,True,3878937,70243.0,35.0,3808659.0

In [27]:
#Referential Integrity
q = f"""
SELECT
    COUNT(*) AS fact_rows,
    COUNT(d.content_hash_id) AS matched_content,
    COUNT(*) - COUNT(d.content_hash_id) AS unmatched_content
FROM {TABLES['fact_daily_sample']} f
LEFT JOIN {TABLES['dim_content']} d
  ON f.client_hash_id = d.client_hash_id
 AND f.content_hash_id = d.content_hash_id
"""

con.execute(q).df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   fact_rows  matched_content  unmatched_content
0   11694072         11694072                  0

In [28]:
#Basic numeric validity
q = f"""
SELECT
    SUM(gsc_impressions < 0) AS negative_impressions,
    SUM(gsc_clicks < 0) AS negative_clicks,
    SUM(ga4_sessions < 0) AS negative_sessions,
    SUM(gsc_avg_position < 0) AS negative_position
FROM {TABLES['fact_daily_sample']}
"""

con.execute(q).df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   negative_impressions  negative_clicks  negative_sessions  negative_position
0                   0.0              0.0                0.0                0.0

###Target/Proxy Field

In [29]:
# Target label should be the opportunity score or rank of the client pages which should have opportunities to get monitored or pruned.

#Example fields are future decline, recovery, top-K action priority, cluster membership
# Target / proxy definition

import pandas as pd

TARGET = {
    "name": "is_declining",
    "type": "binary",
    "meaning": "Future organic-click decline relative to the historical baseline",
    "baseline_window_days": 30,
    "outcome_window_days": 30,
    "threshold": 0.70,
    "rule": "future_30d_clicks < 0.70 * previous_30d_clicks",
}

pd.DataFrame([TARGET])

,name,type,meaning,baseline_window_days,outcome_window_days,threshold,rule
0,is_declining,binary,Future organic-click decline relative to the h...,30,30,0.7,future_30d_clicks < 0.70 * previous_30d_clicks

## Self-check

Before you submit, confirm each line honestly:

- [x] Every section above is filled — markdown thinking AND the code that backs it
- [x] The notebook runs top to bottom with no errors (Runtime → Run all)
- [x] No client names, URLs, or private queries anywhere
- [x] My claims use careful words: observed, measured, directional, decision-support
- [x] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.